## NumPy
+ 계산 과학 분야에 이용되는 핵심 라이브러리
+ 다차원 배열 객체를 연산하는 도구 제공

In [2]:
import numpy as np


In [3]:
# 1차원 배열 생성 
a = np.array([0, 1, 2, 3, 4, 5])
print(a)

[0 1 2 3 4 5]


In [4]:
type(a)

numpy.ndarray

In [5]:
# 2차원 배열 생성
# (실습) 아래와 같이 출력되는 배열 생성하기
# (실행 예시)
# -----------------------------
np.array([[0, 1, 2],
 [3, 4, 5]])
# -----------------------------



array([[0, 1, 2],
       [3, 4, 5]])

## 넘파이 함수 

### - np.zeros()

In [6]:
np.zeros((3,4))#: 0으로 이루어진 배열 생성
# (실습) 3x4 형태의 0으로 이루어진 배열 생성하기
# (실행 예시)
# -----------------------------
# array([[0., 0., 0., 0.],
#        [0., 0., 0., 0.],
#        [0., 0., 0., 0.]])
# -----------------------------


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### - np.ones()

In [7]:
np.ones((2,3))#: 1로 이루어진 배열 생성
# (실습) 2x3 형태의 1로 이루어진 배열 생성
# (실행 예시)
# -----------------------------
# array([[1., 1., 1.],
#        [1., 1., 1.]])
# -----------------------------


array([[1., 1., 1.],
       [1., 1., 1.]])

### - np.arange()

In [8]:
a = np.arange(1,13)#: 특정 범위에 있는 정수 생성; python의 range()와 유사
# (실습) 1부터 12까지의 정수형 원소를 가진 배열 a 생성
# (실행 예시)
# -----------------------------
# array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
# -----------------------------


### - array.reshape()

In [9]:
b = a.reshape((3,4))
# (실습) 위에서 생성한 배열 a를 3x4 형태의 2차원 배열로 재구성한 배열 b 생성
# (실행 예시)
# -----------------------------
# array([[ 1,  2,  3,  4],
#        [ 5,  6,  7,  8],
#        [ 9, 10, 11, 12]])
# -----------------------------
b


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### - np.transpose()

In [10]:
c = np.transpose(b)#: 행과 열을 바꿈 또는 array.T 속성 사용
# (실습) 위에서 변형한 배열 b의 행과 열을 바꿈
# (실행 예시)
# -----------------------------
# array([[ 1,  5,  9],
#        [ 2,  6, 10],
#        [ 3,  7, 11],
#        [ 4,  8, 12]])
# -----------------------------
c

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

## 인덱싱/슬라이싱

In [11]:
# (실습) 아래와 같은 원소와 형태를 가진 2차원 배열 c 생성
# (실행 예시)
# -----------------------------
# array([[ 1,  2,  3,  4,  5],
#        [ 6,  7,  8,  9, 10],
#        [11, 12, 13, 14, 15]])
# -----------------------------
a = np.arange(1,16)
a = a.reshape(3,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
# 인덱싱 - 위 배열 c에서 8의 값 접근
print(a[1][2])

8


In [13]:
# (실습) 슬라이싱을 기능을 이용해 아래처럼 c배열에서 일부만 추출
# (실행 예시)
# ----------------------------- 
# array([[ 9, 10],
#        [14, 15]])
# ----------------------------- 
a[1:3, 3:5]

array([[ 9, 10],
       [14, 15]])

### 배열의 연산

In [14]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# (실습) +, -, *, / ==> 산술연산은 기본적으로 elementwise로 적용

In [15]:
# dot product
# 행렬곱은 @연산자 또는 np.matmul()을 사용할 것을 권장

A @ B
np.matmul(A, B)

array([[19, 22],
       [43, 50]])

In [17]:


n = int(input("3이상의 정수 입력: "))

a = np.ones((n,n))
print(a)
print()
a[1:n-1, 1:n-1] = 0
print(a)

def linear_system_solver(ndarr, v):
    return np.linalg.inv(ndarr) @ v

print(linear_system_solver([[1,1],[2,1]], [15,25]))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
[10.  5.]
